# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pdfcopyUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(736, 681)
        self.input = QtWidgets.QPlainTextEdit(Form)
        self.input.setGeometry(QtCore.QRect(50, 50, 601, 441))
        self.input.setObjectName("input")
        self.deleteEnter = QtWidgets.QPushButton(Form)
        self.deleteEnter.setGeometry(QtCore.QRect(50, 540, 161, 81))
        self.deleteEnter.setObjectName("deleteEnter")
        self.toSentence = QtWidgets.QPushButton(Form)
        self.toSentence.setGeometry(QtCore.QRect(280, 540, 161, 81))
        self.toSentence.setObjectName("toSentence")
        self.copy = QtWidgets.QPushButton(Form)
        self.copy.setGeometry(QtCore.QRect(490, 540, 161, 81))
        self.copy.setObjectName("copy")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(330, 510, 54, 12))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.deleteEnter.setText(_translate("Form", "删除回车符"))
        self.toSentence.setText(_translate("Form", "自动分句"))
        self.copy.setText(_translate("Form", "复制到剪切板"))
        self.label.setText(_translate("Form", "尚未复制"))
